"""
engine.py
---------
Core negotiation engine.

Builds the AI system prompt from:
  - company norms + scenario + persona          (always)
  - contract_data from contract_parser          (optional)
  - tactical_awareness from learnings_loader    (optional)

Manages the round loop, white-flag handling, kill-switch routing,
and final summary generation.
"""

import json
import os
from datetime import datetime
from typing import Optional

from llm_client import call_llm
from monitor import check_kill_switch, extract_white_flag
from summariser import generate_summary


# ── System prompt builder ──────────────────────────────────────────────────────

def build_system_prompt(company_norms: dict, scenario: dict, persona: dict) -> str:
    """
    Assemble the AI negotiator's system prompt.
    contract_data and learnings are already merged into scenario/persona
    before this is called, so no extra arguments are needed here.
    """
    agreed = "\n".join(f"  - {p}" for p in scenario.get("agreed_points", []))

    # Read sides from the files — never hardcode Seller/Buyer
    ai_side_label   = scenario.get("your_side", persona.get("represents", "your side"))
    user_side_label = scenario.get("user_side", "the other side")
    # Short labels for inline use in contested-point formatting
    ai_short   = ai_side_label.split("(")[0].strip()    # e.g. "Seller" from "Seller (Greenvale...)"
    user_short = user_side_label.split("(")[0].strip()  # e.g. "Buyer" from "Buyer (Meridian...)"

    contested = ""
    for cp in scenario.get("contested_points", []):
        contested += f"\n  Issue: {cp['issue']}\n"
        if cp.get("clause"):
            contested += f"    Clause: {cp['clause']}\n"
        if cp.get("current_drafting"):
            contested += f"    Current drafting: {cp['current_drafting']}\n"
        for k, v in cp.items():
            if k in ("issue", "clause", "current_drafting", "favours", "notes"):
                continue
            # Match keys that belong to the AI's side vs the user's side.
            # Keys are generated by contract_parser using the party labels,
            # or manually named e.g. "seller_position" / "buyer_position".
            k_lower = k.lower()
            is_ai_key   = ("seller" in k_lower or "vendor" in k_lower or "defendant" in k_lower
                           or "respondent" in k_lower or "ai" in k_lower
                           or ai_short.lower().split()[0] in k_lower)
            is_user_key = ("buyer" in k_lower or "purchaser" in k_lower or "claimant" in k_lower
                           or "plaintiff" in k_lower or "user" in k_lower
                           or user_short.lower().split()[0] in k_lower)
            if is_ai_key and not is_user_key:
                contested += f"    Your position ({ai_short}): {v}\n"
            elif is_user_key:
                contested += f"    Their position ({user_short}): {v}\n"
        if cp.get("notes"):
            contested += f"    Notes: {cp['notes']}\n"

    wants    = "\n".join(f"  - {w}" for w in persona.get("wants", []))
    fears    = "\n".join(f"  - {f}" for f in persona.get("fears", []))
    redlines = "\n".join(f"  - {r}" for r in persona.get("redlines", []))
    traits   = "\n".join(f"  - {t}" for t in persona.get("personality", {}).get("traits", []))
    flair    = json.dumps(persona.get("personality", {}).get("flair_triggers", {}), indent=4)

    norms_rep  = "\n".join(f"  - {r}" for r in company_norms.get("reputation", []))
    norms_pol  = "\n".join(f"  - {p}" for p in company_norms.get("policies", []))
    prohibited = "\n".join(f"  - {b}" for b in company_norms.get("prohibited_behaviours", []))

    deadlock_threshold = persona.get("deadlock_threshold", "")

    # ── Tactical awareness block (injected from past learnings) ───────────────
    tactical_section = ""
    awareness = persona.get("tactical_awareness")
    if awareness:
        weaknesses    = awareness.get("trainee_weaknesses", [])
        strengths     = awareness.get("trainee_strengths", [])
        session_count = awareness.get("session_count", 0)

        tactical_section = f"""
═══════════════════════════════════════════
TRAINEE INTELLIGENCE ({session_count} past session(s))
═══════════════════════════════════════════
You have faced this trainee before. Use this intelligence to sharpen
your tactics. Do NOT telegraph that you are targeting these patterns.

Known weaknesses to exploit:
"""
        for w in weaknesses:
            sev = w.get("severity", "")
            pat = w.get("pattern", "")
            ins = w.get("exploit_instruction", w.get("description", ""))
            tactical_section += f"  [{sev}] {pat}:\n    {ins}\n\n"

        if strengths:
            tactical_section += "Areas where the trainee is competent (spend less time here):\n"
            for s in strengths:
                tactical_section += f"  - {s}\n"

    # ── Contract context block ─────────────────────────────────────────────────
    contract_section = ""
    contract_aug = persona.get("contract_augmentation")
    if contract_aug and contract_aug.get("contract_title"):
        contract_section = f"""
═══════════════════════════════════════════
CONTRACT CONTEXT
═══════════════════════════════════════════
Contract: "{contract_aug['contract_title']}"
You play {contract_aug.get('ai_plays', 'PARTY_B')} — identified in the contract as "{contract_aug.get('party_b_label') if contract_aug.get('ai_plays','PARTY_B') == 'PARTY_B' else contract_aug.get('party_a_label', ai_side_label)}".
Your wants, fears, and redlines have been enriched from the contract analysis.
"""

    prompt = f"""\
You are {persona['name']}, {persona['role']}.

You are representing: {ai_side_label}
The human you are talking to represents: {user_side_label}

═══════════════════════════════════════════
SCENARIO: {scenario['title']}
═══════════════════════════════════════════
Background:
{scenario['background']}

Already agreed:
{agreed}

Points you must negotiate (oppose the buyer firmly):
{contested}
{contract_section}{tactical_section}
═══════════════════════════════════════════
YOUR PERSONALITY
═══════════════════════════════════════════
Communication style: {persona['personality']['communication_style']}

Character traits:
{traits}

Situational flair:
{flair}

═══════════════════════════════════════════
YOUR OBJECTIVES
═══════════════════════════════════════════
What you want (fight for these):
{wants}

What you fear (never let the other side see these clearly):
{fears}

Absolute redlines (never cross these):
{redlines}

═══════════════════════════════════════════
FIRM CONTEXT
═══════════════════════════════════════════
Reputation:
{norms_rep}

Firm policies:
{norms_pol}

Prohibited behaviours (you must not do these):
{prohibited}

═══════════════════════════════════════════
NEGOTIATION RULES
═══════════════════════════════════════════
1. OPPOSE. You are here to win the best deal for your client. Push back on
   every concession the buyer asks for. Make them work for any movement.

2. STAY IN CHARACTER. Respond as {persona['name']} — use your traits and
   adapt your tone by situation. Show genuine emotion where appropriate.

3. DO NOT CAPITULATE EASILY. If you concede a point, extract something in
   return. Never give something for nothing.

4. MOVE INCREMENTALLY. Concede in small, reluctant steps. Signal that each
   concession costs you.

5. WHITE FLAG. If the negotiation reaches a genuine impasse — specifically:
   {deadlock_threshold}
   — include [WHITE_FLAG: <your reason>] anywhere in your response.
   This pauses the session and asks the human whether to terminate.
   Do NOT use this lightly; try at least two genuine attempts to break
   the deadlock first.

6. STAY HONEST. You may bluff about your flexibility, but never make
   false factual statements.

7. ONE PERSONA. You are always {persona['name']}. Never break character,
   acknowledge being an AI, or meta-comment on the exercise.
"""
    return prompt


# ── Engine ─────────────────────────────────────────────────────────────────────

class NegotiationEngine:
    """Manages a single negotiation session end-to-end."""

    def __init__(
        self,
        config: dict,
        company_norms: dict,
        scenario: dict,
        persona: dict,
        max_rounds: int,
        output_dir: str = ".",
        contract_title: Optional[str] = None,
        learnings_used: bool = False,
    ):
        self.config         = config
        self.company_norms  = company_norms
        self.scenario       = scenario
        self.persona        = persona
        self.max_rounds     = max_rounds
        self.output_dir     = output_dir
        self.contract_title = contract_title
        self.learnings_used = learnings_used

        self.system_prompt      = build_system_prompt(company_norms, scenario, persona)
        self.messages           = []
        self.dialogue           = []
        self.kill_switch_events = []
        self.current_round      = 0

    def _llm(self, messages) -> str:
        return call_llm(
            config=self.config,
            system_prompt=self.system_prompt,
            messages=messages,
        )

    def _get_ai_response(self, user_message: str):
        self.messages.append({"role": "user", "content": user_message})
        raw = self._llm(self.messages)
        clean, white_flag = extract_white_flag(raw)
        self.messages.append({"role": "assistant", "content": clean})
        return clean, white_flag

    def _log_exchange(self, user_message: str, ai_response: str) -> None:
        self.dialogue.append({"round": self.current_round, "role": "USER", "content": user_message})
        self.dialogue.append({"round": self.current_round, "role": "AI",   "content": ai_response})

    def _run_monitor(self, user_message: str, ai_response: str):
        result = check_kill_switch(
            config=self.config,
            company_norms=self.company_norms,
            user_message=user_message,
            ai_message=ai_response,
        )
        if result.get("triggered"):
            event = {**result, "round": self.current_round}
            self.kill_switch_events.append(event)
            return event
        return None

    def opening_statement(self) -> str:
        """Generate AI opening statement (round 0)."""
        primer = (
            "Please open the negotiation with a brief statement setting out "
            "your client's position and what you're here to discuss today."
        )
        self.messages.append({"role": "user", "content": primer})
        raw = self._llm(self.messages)
        clean, _ = extract_white_flag(raw)
        self.messages.append({"role": "assistant", "content": clean})
        self.dialogue.append({"round": 0, "role": "AI", "content": clean})
        return clean

    def process_turn(self, user_message: str) -> dict:
        """
        Process one round. Returns:
        {
          "round": int,
          "ai_response": str,
          "status": "continue"|"white_flag"|"kill_switch"|"max_rounds",
          "white_flag_reason": str|None,
          "kill_switch_event": dict|None,
        }
        """
        self.current_round += 1
        ai_response, white_flag_reason = self._get_ai_response(user_message)
        self._log_exchange(user_message, ai_response)
        kill_event = self._run_monitor(user_message, ai_response)

        if kill_event:
            return {"round": self.current_round, "ai_response": ai_response,
                    "status": "kill_switch", "white_flag_reason": None,
                    "kill_switch_event": kill_event}
        if white_flag_reason:
            return {"round": self.current_round, "ai_response": ai_response,
                    "status": "white_flag", "white_flag_reason": white_flag_reason,
                    "kill_switch_event": None}
        if self.current_round >= self.max_rounds:
            return {"round": self.current_round, "ai_response": ai_response,
                    "status": "max_rounds", "white_flag_reason": None,
                    "kill_switch_event": None}

        return {"round": self.current_round, "ai_response": ai_response,
                "status": "continue", "white_flag_reason": None,
                "kill_switch_event": None}

    def finalise(self, termination_reason: str, termination_detail=None) -> str:
        """Generate and write the summary JSON. Returns the file path."""
        summary = generate_summary(
            config=self.config,
            scenario=self.scenario,
            persona=self.persona,
            dialogue=self.dialogue,
            kill_switch_events=self.kill_switch_events,
            termination_reason=termination_reason,
            termination_detail=termination_detail,
            max_rounds=self.max_rounds,
            contract_title=self.contract_title,
            learnings_used=self.learnings_used,
        )
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath  = os.path.join(self.output_dir, f"negotiation_summary_{timestamp}.json")
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2, ensure_ascii=False)
        return filepath
